const root=document.getElementById('farmNotes'),config=window.LE_SANCTUAIRE_FIREBASE;
const TAGS=['pollinator','fire','flowering','animal interaction','abundance','location','propagation'];
let api,db,auth,user,species,notes=[],editing,unsubscribe;
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const message=(title,body)=>root.innerHTML=`<div class="notesState"><b>${esc(title)}</b><span>${esc(body)}</span></div>`;
function render(){
 if(!config){message('Farm Notes are not configured','The field guide and iNaturalist sync continue normally. Complete the Firebase steps in README.md to enable private notes.');return}
 if(!api){message('Connecting to Farm Notes','Firebase is loading. The rest of this species card remains available.');return}
 if(!user){root.innerHTML=`<div class="notesState"><b>Private Farm Notes</b><span>Sign in with the single-owner Firebase account.</span></div><form id="notesLogin" class="noteForm"><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="btn" type="submit">Sign in</button><span id="notesError" class="formError"></span></form>`;document.getElementById('notesLogin').onsubmit=login;return}
 const list=notes.length?notes.map(n=>`<article class="farmNote"><div class="noteTop"><time>${esc(n.date||'Undated')}</time><span><button data-edit="${esc(n.id)}">Edit</button><button data-delete="${esc(n.id)}">Delete</button></span></div><p>${esc(n.text)}</p>${n.location?`<div class="noteLocation">📍 ${esc(n.location)}</div>`:''}<div class="tags">${(n.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></article>`).join(''):'<div class="ecoEmpty">No farm notes for this species yet.</div>';
 const current=editing?notes.find(n=>n.id===editing):null;
 root.innerHTML=`<div class="notesHead"><div><b>Le Sanctuaire Farm Notes</b><span>Private notes saved in Firestore</span></div><button id="notesSignOut" class="textBtn">Sign out</button></div>${list}<form id="noteForm" class="noteForm"><h5>${current?'Edit note':'Add a farm note'}</h5><label>Date<input name="date" type="date" value="${esc(current?.date||new Date().toISOString().slice(0,10))}" required></label><label>Observation<textarea name="text" rows="3" maxlength="2000" required>${esc(current?.text||'')}</textarea></label><label>Location or habitat (optional)<input name="location" maxlength="300" value="${esc(current?.location||'')}"></label><fieldset><legend>Tags</legend><div class="tagChecks">${TAGS.map(t=>`<label><input type="checkbox" name="tags" value="${t}" ${(current?.tags||[]).includes(t)?'checked':''}> ${t}</label>`).join('')}</div></fieldset><div class="formActions"><button class="btn" type="submit">${current?'Save changes':'Add note'}</button>${current?'<button id="cancelEdit" class="secondaryBtn" type="button">Cancel</button>':''}</div><span id="notesError" class="formError"></span></form>`;
 root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;render()});root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeNote(b.dataset.delete));document.getElementById('noteForm').onsubmit=saveNote;document.getElementById('notesSignOut').onclick=()=>api.signOut(auth);if(current)document.getElementById('cancelEdit').onclick=()=>{editing=null;render()};
}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await api.signInWithEmailAndPassword(auth,f.get('email'),f.get('password'))}catch{document.getElementById('notesError').textContent='Sign-in failed. Check the email/password and Firebase Authentication setup.'}}
async function saveNote(e){e.preventDefault();const f=new FormData(e.currentTarget),payload={taxonKey:species.taxonKey,scientificName:species.scientific,commonName:species.common,date:f.get('date'),text:String(f.get('text')).trim(),location:String(f.get('location')).trim(),tags:f.getAll('tags'),ownerUid:user.uid,updatedAt:api.serverTimestamp()};try{if(editing)await api.updateDoc(api.doc(db,'farmNotes',editing),payload);else await api.addDoc(api.collection(db,'farmNotes'),{...payload,createdAt:api.serverTimestamp()});editing=null}catch{document.getElementById('notesError').textContent='Could not save. Check the connection and Firestore rules.'}}
async function removeNote(id){if(!confirm('Delete this farm note?'))return;try{await api.deleteDoc(api.doc(db,'farmNotes',id))}catch{alert('Could not delete. Check the connection and Firestore rules.')}}
function listen(){unsubscribe?.();notes=[];editing=null;if(!species||!user){render();return}const q=api.query(api.collection(db,'farmNotes'),api.where('taxonKey','==',species.taxonKey));unsubscribe=api.onSnapshot(q,s=>{notes=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.date||'').localeCompare(a.date||''));render()},error=>{console.error('Farm Notes listener failed',error);const code=error?.code||'unknown';message('Farm Notes temporarily unavailable',`Firebase error: ${code}. The app and iNaturalist sync are still working.`)})}
window.FarmNotes={openSpecies(value){species=value;listen()}};
if(!config)render();else Promise.all([import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js')]).then(([app,store,authApi])=>{const instance=app.initializeApp(config);db=store.getFirestore(instance);auth=authApi.getAuth(instance);api={...store,...authApi};authApi.onAuthStateChanged(auth,value=>{user=value;listen()})}).catch(()=>message('Farm Notes temporarily unavailable','Firebase could not load. The app and iNaturalist sync continue normally.'));
